[package]
name = "eucarinogammarus_db"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
eframe = "0.22.0"
egui = "0.22.0"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }